import type { Locale } from "./locales";

type UiCopy = {
  pageTitle: string;
  pageDescription: string;
  nav: { latest: string; archive: string; methodology: string; languages: string };
  skip: string;
  home: {
    eyebrow: string;
    headline: string;
    intro: string;
    latest: string;
    all: string;
    read: string;
    numbers: string;
    framework: string;
    reviewed: string;
    desk: string;
    scope: string;
    meetings: string;
    winRate: string;
    winnerMinute: string;
    emptyTitle: string;
    emptyBody: string;
    cards: [string, string][];
  };
  archive: { title: string; intro: string; empty: string };
  method: {
    title: string;
    intro: string;
    flow: string;
    steps: [string, string][];
    policy: string;
  };
  article: {
    reviewed: string;
    confidence: string;
    historicalSample: string;
    matches: string;
    contentType: string;
    postMatch: string;
    fact: string;
    outcome: string;
    share: string;
    wins: string;
    draws: string;
    change: string;
    analysis: string;
    reading: string;
    evidence: string;
  };
  footer: string;
};

export const ui: Record<Locale, UiCopy> = {
  zh: {
    pageTitle: "赛后足球分析", pageDescription: "用历史交锋、人员变化和比赛证据解释足球赛果。", skip: "跳到正文",
    nav: { latest: "最新", archive: "归档", methodology: "方法", languages: "语言" },
    home: {
      eyebrow: "独立足球分析 · 简体中文版", headline: "终场之后，\n才开始解释。", intro: "不追逐实时喧嚣。我们回到历史交锋、人员变化与比赛证据，解释一个结果为何发生。", latest: "最新分析", all: "查看全部文章", read: "阅读全文", numbers: "本期数字", framework: "我们的分析框架", reviewed: "已审核", desk: "编辑部在线", scope: "全球足球 · 仅限赛后", meetings: "赛前历史交锋", winRate: "历史胜率", winnerMinute: "制胜球时间", emptyTitle: "本语言版本正在编译中", emptyBody: "栏目已经开放；只有完成本语言翻译、数字一致性校验和人工审核的文章才会出现。",
      cards: [["历史不是预测", "交锋次数和胜率提供背景，但不会替代对当下阵容的判断。"], ["变化必须可解释", "教练、首发、伤停与换人分别说明胜率为何可能移动。"], ["结果必须回到证据", "关键事件解释比分，观点与事实始终明确分开。"]],
    },
    archive: { title: "文章归档", intro: "按终场时间整理的赛后历史分析。只收录经过人工审核并正式发布的文章。", empty: "本语言版本暂时没有已审核文章。" },
    method: { title: "我们如何解释一场比赛", intro: "数据决定事实边界，编辑判断决定文章质量。AI 可以整理证据，但不能替代审核。", flow: "事实 → 计算 → 分析 → 人工审核 → 发布", steps: [["01 · 先确定事实", "赛果、阵容与关键事件至少由两个独立的已授权来源核对。冲突未解决时禁止发布。"], ["02 · 再做确定性计算", "交锋、胜率、阵容延续率和比分由程序计算，AI 不补全缺失数字。"], ["03 · 区分事实与判断", "核验记录属于事实；文章只把有证据支持的机制写成分析。"], ["04 · 人工最终决定", "AI 只生成草稿。编辑检查数字、措辞、授权和各语言一致性。"], ["05 · 不发布赛事视觉素材", "公开页面没有截图、照片、视频、头像或队徽；本地临时素材在任务结束后删除。"]], policy: "无实时比分、账户、评论、用户投稿、行为画像或个性化内容。" },
    article: { reviewed: "人工审核", confidence: "分析置信度", historicalSample: "历史样本", matches: "场", contentType: "内容类型", postMatch: "赛后历史解读", fact: "事实", outcome: "结果", share: "占比", wins: "胜", draws: "平局", change: "变化", analysis: "分析", reading: "判断", evidence: "证据置信度" },
    footer: "Event Analysis 是一个只做赛后历史解读的独立静态内容门户。无实时比分、无账户、无用户追踪。",
  },
  "zh-hant": {
    pageTitle: "賽後足球分析", pageDescription: "用歷史交鋒、人員變化和比賽證據解釋足球賽果。", skip: "跳至正文",
    nav: { latest: "最新", archive: "歸檔", methodology: "方法", languages: "語言" },
    home: { eyebrow: "獨立足球分析 · 繁體中文版", headline: "終場之後，\n才開始解釋。", intro: "不追逐即時喧囂。我們回到歷史交鋒、人員變化與比賽證據，解釋結果為何發生。", latest: "最新分析", all: "查看所有文章", read: "閱讀全文", numbers: "本期數字", framework: "我們的分析框架", reviewed: "已審核", desk: "編輯部在線", scope: "全球足球 · 僅限賽後", meetings: "賽前歷史交鋒", winRate: "歷史勝率", winnerMinute: "致勝球時間", emptyTitle: "本語言版本正在編譯中", emptyBody: "欄目已開放；只有完成翻譯、數字一致性檢查及人工審核的文章才會出現。", cards: [["歷史不是預測", "交鋒與勝率提供背景，不能取代對當前陣容的判斷。"], ["變化必須可解釋", "教練、正選、傷停與換人說明形勢如何移動。"], ["結果必須回到證據", "關鍵事件解釋比分，事實與觀點清楚分開。"]] },
    archive: { title: "文章歸檔", intro: "按終場時間整理的賽後歷史分析，只收錄人工審核內容。", empty: "本語言版本暫無已審核文章。" },
    method: { title: "我們如何解釋一場比賽", intro: "數據決定事實邊界，編輯判斷決定文章品質。AI 不能取代審核。", flow: "事實 → 計算 → 分析 → 人工審核 → 發布", steps: [["01 · 確定事實", "賽果、陣容及事件由至少兩個獨立授權來源核對。"], ["02 · 確定性計算", "交鋒、勝率與比分由程式計算，AI 不填補缺失數字。"], ["03 · 分開事實與判斷", "核驗記錄是事實；有證據支持的機制才寫成分析。"], ["04 · 人工最終決定", "AI 只寫草稿，編輯檢查數字、權利與各語言一致性。"], ["05 · 不發布視覺素材", "公開頁面沒有賽事圖片或影片；臨時素材在任務後刪除。"]], policy: "無即時比分、帳戶、評論、投稿、用戶追蹤或個人化內容。" },
    article: { reviewed: "人工審核", confidence: "分析可信度", historicalSample: "歷史樣本", matches: "場", contentType: "內容類型", postMatch: "賽後歷史解讀", fact: "事實", outcome: "結果", share: "佔比", wins: "勝", draws: "和局", change: "變化", analysis: "分析", reading: "判斷", evidence: "證據可信度" },
    footer: "Event Analysis 是專注賽後歷史解讀的獨立靜態內容網站，沒有即時比分、帳戶或用戶追蹤。",
  },
  en: {
    pageTitle: "Post-match football analysis", pageDescription: "Football results explained through history, personnel changes and match evidence.", skip: "Skip to content",
    nav: { latest: "Latest", archive: "Archive", methodology: "Method", languages: "Languages" },
    home: { eyebrow: "Independent football analysis · English edition", headline: "The whistle ends it.\nThe explanation starts.", intro: "No live noise. We return to the record, the personnel changes and the match evidence to explain why a result happened.", latest: "Latest analysis", all: "View the full archive", read: "Read the analysis", numbers: "The numbers", framework: "Our analytical frame", reviewed: "Reviewed", desk: "Editorial desk active", scope: "Global football · Post-match only", meetings: "meetings before the match", winRate: "historical win rate", winnerMinute: "minute of the winner", emptyTitle: "This edition is being assembled", emptyBody: "The section is open. Articles appear only after translation, numerical consistency checks and human review.", cards: [["History is not a forecast", "Meetings and win rates create context; they do not replace a view of the current team."], ["Change needs a mechanism", "Coaches, line-ups, absences and substitutions explain why the balance may move."], ["The result returns to evidence", "Key events explain the score, with facts and interpretation kept visibly separate."]] },
    archive: { title: "Article archive", intro: "Post-match historical analysis ordered by the final whistle. Only human-reviewed work is published.", empty: "No reviewed articles are available in this language yet." },
    method: { title: "How we explain a football match", intro: "Data sets the boundary of fact. Editorial judgement sets the standard. AI can organise evidence; it cannot approve publication.", flow: "Facts → Calculation → Analysis → Human review → Publication", steps: [["01 · Establish the facts", "Scores, line-ups and key events are checked against at least two independent authorised sources."], ["02 · Calculate deterministically", "Meetings, win rates, continuity and scores are calculated in code; AI does not invent missing numbers."], ["03 · Separate fact from interpretation", "Verified records are facts. Only evidence-backed mechanisms are presented as analysis."], ["04 · Humans make the final call", "AI produces drafts. Editors check numbers, language, rights and consistency across editions."], ["05 · Publish no match media", "Public pages contain no match images or video. Temporary local media is deleted when each job ends."]], policy: "No live scores, accounts, comments, submissions, behavioural profiles or personalised content." },
    article: { reviewed: "Human reviewed", confidence: "Analysis confidence", historicalSample: "Historical sample", matches: "matches", contentType: "Content type", postMatch: "Post-match review", fact: "Fact", outcome: "Outcome", share: "Share", wins: "wins", draws: "Draws", change: "Change", analysis: "Analysis", reading: "Reading", evidence: "Evidence confidence" },
    footer: "Event Analysis is an independent static publication for post-match historical analysis. No live scores, accounts or user tracking.",
  },
  ja: {
    pageTitle: "試合後のサッカー分析", pageDescription: "対戦史、選手の変化、試合の証拠から結果を読み解きます。", skip: "本文へ移動",
    nav: { latest: "最新", archive: "アーカイブ", methodology: "分析方法", languages: "言語" },
    home: { eyebrow: "独立系サッカー分析 · 日本語版", headline: "試合が終わって、\n説明が始まる。", intro: "速報の熱狂ではなく、対戦史、人員の変化、試合の証拠から結果の理由を考えます。", latest: "最新の分析", all: "全記事を見る", read: "分析を読む", numbers: "数字", framework: "分析の枠組み", reviewed: "審査済み", desk: "編集部稼働中", scope: "世界のサッカー · 試合後のみ", meetings: "試合前の対戦数", winRate: "過去の勝率", winnerMinute: "決勝点の時間", emptyTitle: "日本語版を準備中です", emptyBody: "翻訳、数値の整合性確認、人による審査を終えた記事だけを掲載します。", cards: [["歴史は予言ではない", "対戦数と勝率は背景であり、現在のチーム評価の代わりではありません。"], ["変化には仕組みがある", "監督、先発、欠場、交代が力関係の変化を説明します。"], ["結果を証拠に戻す", "重要場面で得点を説明し、事実と解釈を分けます。"]] },
    archive: { title: "記事アーカイブ", intro: "試合終了時刻順の歴史分析。人が審査した記事のみ公開します。", empty: "日本語で審査済みの記事はまだありません。" },
    method: { title: "試合をどう説明するか", intro: "データが事実の境界を決め、編集判断が品質を決めます。AI は公開を承認できません。", flow: "事実 → 計算 → 分析 → 人の審査 → 公開", steps: [["01 · 事実を確定", "結果、先発、重要場面を二つ以上の独立した許諾済み情報源で確認します。"], ["02 · 決定的に計算", "対戦数、勝率、継続率、得点はコードで計算します。"], ["03 · 事実と解釈を分離", "確認記録を事実とし、根拠のある仕組みだけを分析とします。"], ["04 · 最終判断は人", "AI は下書きのみ。編集者が数値、表現、権利、各言語の一致を確認します。"], ["05 · 試合映像を掲載しない", "画像や動画は公開せず、一時素材は処理後に削除します。"]], policy: "速報、アカウント、コメント、投稿、追跡、個人向け表示はありません。" },
    article: { reviewed: "人による審査済み", confidence: "分析の確度", historicalSample: "過去の標本", matches: "試合", contentType: "記事種別", postMatch: "試合後の歴史分析", fact: "事実", outcome: "結果", share: "割合", wins: "勝", draws: "引分", change: "変化", analysis: "分析", reading: "解釈", evidence: "証拠の確度" },
    footer: "Event Analysis は試合後の歴史分析に特化した独立系静的メディアです。速報、アカウント、追跡はありません。",
  },
  ko: {
    pageTitle: "경기 후 축구 분석", pageDescription: "상대 전적, 인원 변화와 경기 근거로 결과를 설명합니다.", skip: "본문으로 이동",
    nav: { latest: "최신", archive: "아카이브", methodology: "방법론", languages: "언어" },
    home: { eyebrow: "독립 축구 분석 · 한국어판", headline: "경기가 끝나면,\n설명이 시작됩니다.", intro: "실시간 소음 대신 상대 전적, 인원 변화와 경기 근거로 결과가 나온 이유를 살핍니다.", latest: "최신 분석", all: "전체 글 보기", read: "분석 읽기", numbers: "주요 수치", framework: "분석 프레임", reviewed: "검토 완료", desk: "편집부 운영 중", scope: "세계 축구 · 경기 후만", meetings: "경기 전 맞대결", winRate: "역대 승률", winnerMinute: "결승골 시간", emptyTitle: "한국어판을 준비하고 있습니다", emptyBody: "번역, 수치 일치 검사와 사람의 검토를 마친 글만 게시합니다.", cards: [["역사는 예측이 아닙니다", "전적과 승률은 배경이며 현재 전력을 대신하지 않습니다."], ["변화에는 이유가 필요합니다", "감독, 선발, 결장과 교체가 균형의 이동을 설명합니다."], ["결과는 근거로 돌아갑니다", "주요 사건으로 점수를 설명하고 사실과 해석을 구분합니다."]] },
    archive: { title: "글 아카이브", intro: "경기 종료 순으로 정리한 사후 역사 분석입니다. 사람의 검토를 통과한 글만 공개합니다.", empty: "아직 한국어로 검토된 글이 없습니다." },
    method: { title: "경기를 설명하는 방법", intro: "데이터가 사실의 경계를 정하고 편집 판단이 품질을 정합니다. AI는 공개를 승인하지 않습니다.", flow: "사실 → 계산 → 분석 → 사람 검토 → 공개", steps: [["01 · 사실 확인", "결과, 라인업과 주요 사건을 두 개 이상의 독립된 허가 출처로 확인합니다."], ["02 · 결정론적 계산", "전적, 승률, 연속성과 점수는 코드로 계산합니다."], ["03 · 사실과 해석 분리", "검증 기록은 사실이며 근거 있는 메커니즘만 분석으로 제시합니다."], ["04 · 최종 결정은 사람", "AI는 초안만 작성하고 편집자가 수치, 표현, 권리와 언어 일치를 봅니다."], ["05 · 경기 미디어 미게시", "공개 페이지에 사진과 영상이 없으며 임시 자료는 작업 후 삭제합니다."]], policy: "실시간 점수, 계정, 댓글, 투고, 추적이나 개인화가 없습니다." },
    article: { reviewed: "사람 검토 완료", confidence: "분석 신뢰도", historicalSample: "역대 표본", matches: "경기", contentType: "콘텐츠 유형", postMatch: "경기 후 역사 분석", fact: "사실", outcome: "결과", share: "비율", wins: "승", draws: "무승부", change: "변화", analysis: "분석", reading: "판단", evidence: "근거 신뢰도" },
    footer: "Event Analysis는 경기 후 역사 분석만 다루는 독립 정적 매체입니다. 실시간 점수, 계정, 사용자 추적이 없습니다.",
  },
  ru: {
    pageTitle: "Послематчевый анализ футбола", pageDescription: "Объясняем результат через историю встреч, изменения состава и факты матча.", skip: "К материалу",
    nav: { latest: "Новое", archive: "Архив", methodology: "Метод", languages: "Языки" },
    home: { eyebrow: "Независимый анализ футбола · Русская версия", headline: "Матч окончен.\nОбъяснение начинается.", intro: "Без шума прямого эфира. История встреч, изменения состава и факты матча объясняют итог.", latest: "Последний анализ", all: "Весь архив", read: "Читать анализ", numbers: "Цифры", framework: "Схема анализа", reviewed: "Проверено", desk: "Редакция работает", scope: "Мировой футбол · После матча", meetings: "встреч до матча", winRate: "исторический процент побед", winnerMinute: "минута победного гола", emptyTitle: "Русская версия готовится", emptyBody: "Публикуются только переведённые, сверенные по цифрам и проверенные редактором материалы.", cards: [["История не прогноз", "Очные встречи дают контекст, но не заменяют оценку текущего состава."], ["Изменения требуют механизма", "Тренер, старт, потери и замены показывают сдвиг баланса."], ["Итог возвращается к фактам", "Ключевые эпизоды объясняют счёт; факты отделены от выводов."]] },
    archive: { title: "Архив статей", intro: "Исторический анализ после финального свистка. Только материалы с ручной проверкой.", empty: "Проверенных статей на русском пока нет." },
    method: { title: "Как мы объясняем матч", intro: "Данные задают границы фактов, редактор — стандарт качества. AI не утверждает публикацию.", flow: "Факты → Расчёт → Анализ → Редактор → Публикация", steps: [["01 · Установить факты", "Счёт, составы и события сверяются минимум по двум независимым разрешённым источникам."], ["02 · Считать программно", "Встречи, проценты, преемственность и счёт рассчитывает код."], ["03 · Отделить выводы", "Проверенные записи — факты; анализом становятся только обоснованные механизмы."], ["04 · Решение за человеком", "AI пишет черновик, редактор проверяет цифры, права и согласованность языков."], ["05 · Без медиа матча", "На сайте нет фото и видео; временные материалы удаляются после задачи."]], policy: "Нет лайв-скоров, аккаунтов, комментариев, заявок, слежения или персонализации." },
    article: { reviewed: "Проверено человеком", confidence: "Уверенность анализа", historicalSample: "Историческая выборка", matches: "матчей", contentType: "Тип материала", postMatch: "Послематчевый разбор", fact: "Факт", outcome: "Итог", share: "Доля", wins: "победы", draws: "Ничьи", change: "Изменение", analysis: "Анализ", reading: "Вывод", evidence: "Уверенность в фактах" },
    footer: "Event Analysis — независимое статическое издание о послематчевой истории. Без лайв-скоров, аккаунтов и слежения.",
  },
  es: {
    pageTitle: "Análisis de fútbol después del partido", pageDescription: "Explicamos el resultado con antecedentes, cambios de personal y pruebas del partido.", skip: "Ir al contenido",
    nav: { latest: "Último", archive: "Archivo", methodology: "Método", languages: "Idiomas" },
    home: { eyebrow: "Análisis independiente · Edición en español", headline: "Termina el partido.\nEmpieza la explicación.", intro: "Sin ruido en directo. Volvemos al historial, los cambios de personal y las pruebas del partido para explicar el resultado.", latest: "Último análisis", all: "Ver todo el archivo", read: "Leer el análisis", numbers: "Las cifras", framework: "Nuestro marco", reviewed: "Revisado", desk: "Redacción activa", scope: "Fútbol mundial · Solo pospartido", meetings: "duelos antes del partido", winRate: "porcentaje histórico de victorias", winnerMinute: "minuto del gol ganador", emptyTitle: "Estamos preparando esta edición", emptyBody: "Solo aparecen artículos traducidos, comprobados en sus cifras y revisados por una persona.", cards: [["La historia no predice", "Los duelos y porcentajes dan contexto, no sustituyen al equipo actual."], ["El cambio necesita un mecanismo", "Entrenador, once, bajas y cambios explican el movimiento del equilibrio."], ["El resultado vuelve a la prueba", "Los episodios explican el marcador y separan hechos de interpretación."]] },
    archive: { title: "Archivo de artículos", intro: "Análisis histórico pospartido ordenado por el pitido final. Solo trabajo revisado.", empty: "Todavía no hay artículos revisados en español." },
    method: { title: "Cómo explicamos un partido", intro: "Los datos fijan el límite de los hechos; el criterio editorial fija la calidad. La IA no aprueba publicaciones.", flow: "Hechos → Cálculo → Análisis → Revisión humana → Publicación", steps: [["01 · Establecer los hechos", "Resultado, alineaciones y eventos se contrastan con dos fuentes independientes autorizadas."], ["02 · Calcular de forma determinista", "Duelos, porcentajes, continuidad y marcador se calculan mediante código."], ["03 · Separar hecho e interpretación", "Los registros verificados son hechos; solo los mecanismos con pruebas son análisis."], ["04 · Decide una persona", "La IA redacta borradores; el editor revisa cifras, lenguaje, derechos e idiomas."], ["05 · Sin imágenes del partido", "No publicamos fotos ni vídeo; el material temporal se elimina al terminar."]], policy: "Sin marcadores en vivo, cuentas, comentarios, envíos, perfiles ni personalización." },
    article: { reviewed: "Revisión humana", confidence: "Confianza del análisis", historicalSample: "Muestra histórica", matches: "partidos", contentType: "Tipo de contenido", postMatch: "Análisis pospartido", fact: "Hecho", outcome: "Resultado", share: "Proporción", wins: "victorias", draws: "Empates", change: "Cambio", analysis: "Análisis", reading: "Lectura", evidence: "Confianza de la evidencia" },
    footer: "Event Analysis es una publicación estática e independiente de análisis histórico pospartido. Sin directos, cuentas ni rastreo.",
  },
  pt: {
    pageTitle: "Análise de futebol pós-jogo", pageDescription: "Explicamos resultados por confrontos, mudanças de pessoal e evidências da partida.", skip: "Ir para o conteúdo",
    nav: { latest: "Últimas", archive: "Arquivo", methodology: "Método", languages: "Idiomas" },
    home: { eyebrow: "Análise independente · Edição em português", headline: "O jogo termina.\nA explicação começa.", intro: "Sem ruído ao vivo. Voltamos ao histórico, às mudanças e às evidências para explicar o resultado.", latest: "Última análise", all: "Ver o arquivo", read: "Ler análise", numbers: "Os números", framework: "Nosso método", reviewed: "Revisado", desk: "Redação ativa", scope: "Futebol global · Só pós-jogo", meetings: "confrontos antes do jogo", winRate: "taxa histórica de vitórias", winnerMinute: "minuto do gol da vitória", emptyTitle: "Esta edição está em preparação", emptyBody: "Só publicamos textos traduzidos, com números consistentes e revisão humana.", cards: [["História não é previsão", "Confrontos e taxas dão contexto, mas não substituem o elenco atual."], ["Mudança exige mecanismo", "Técnico, escalação, ausências e substituições explicam o equilíbrio."], ["O resultado volta à evidência", "Eventos explicam o placar; fatos e leitura ficam separados."]] },
    archive: { title: "Arquivo de artigos", intro: "Análise histórica pós-jogo em ordem de apito final. Apenas conteúdo revisado.", empty: "Ainda não há artigos revisados em português." },
    method: { title: "Como explicamos uma partida", intro: "Dados limitam os fatos; julgamento editorial define a qualidade. A IA não aprova publicação.", flow: "Fatos → Cálculo → Análise → Revisão humana → Publicação", steps: [["01 · Confirmar fatos", "Placar, escalações e eventos passam por duas fontes independentes autorizadas."], ["02 · Calcular no código", "Confrontos, taxas, continuidade e placar são cálculos determinísticos."], ["03 · Separar interpretação", "Registros verificados são fatos; só mecanismos apoiados viram análise."], ["04 · Decisão humana", "A IA escreve rascunhos; editores verificam números, direitos e idiomas."], ["05 · Sem mídia da partida", "Não publicamos fotos ou vídeo; o material temporário é apagado no fim."]], policy: "Sem placar ao vivo, contas, comentários, envios, perfis ou personalização." },
    article: { reviewed: "Revisão humana", confidence: "Confiança da análise", historicalSample: "Amostra histórica", matches: "jogos", contentType: "Tipo de conteúdo", postMatch: "Análise pós-jogo", fact: "Fato", outcome: "Resultado", share: "Proporção", wins: "vitórias", draws: "Empates", change: "Mudança", analysis: "Análise", reading: "Leitura", evidence: "Confiança da evidência" },
    footer: "Event Analysis é uma publicação estática independente de análise histórica pós-jogo. Sem placar ao vivo, contas ou rastreamento.",
  },
  fr: {
    pageTitle: "Analyse du football après-match", pageDescription: "Le résultat expliqué par l'historique, les changements d'effectif et les faits du match.", skip: "Aller au contenu",
    nav: { latest: "Récent", archive: "Archives", methodology: "Méthode", languages: "Langues" },
    home: { eyebrow: "Analyse indépendante · Édition française", headline: "Le match se termine.\nL'explication commence.", intro: "Pas de bruit en direct. L'historique, les changements et les faits du match expliquent le résultat.", latest: "Dernière analyse", all: "Voir les archives", read: "Lire l'analyse", numbers: "Les chiffres", framework: "Notre cadre", reviewed: "Relu", desk: "Rédaction active", scope: "Football mondial · Après-match", meetings: "rencontres avant le match", winRate: "taux historique de victoire", winnerMinute: "minute du but décisif", emptyTitle: "Cette édition est en préparation", emptyBody: "Seuls les articles traduits, vérifiés numériquement et relus par une personne sont publiés.", cards: [["L'histoire n'est pas une prévision", "Les confrontations donnent du contexte, pas une évaluation de l'équipe actuelle."], ["Le changement exige un mécanisme", "Entraîneur, onze, absences et remplacements expliquent l'équilibre."], ["Le résultat revient aux preuves", "Les actions expliquent le score; faits et interprétation restent séparés."]] },
    archive: { title: "Archives des articles", intro: "Analyses historiques après-match classées au coup de sifflet. Uniquement les textes relus.", empty: "Aucun article relu en français pour le moment." },
    method: { title: "Comment nous expliquons un match", intro: "Les données bornent les faits; le jugement éditorial fixe la qualité. L'IA ne valide pas la publication.", flow: "Faits → Calcul → Analyse → Relecture humaine → Publication", steps: [["01 · Établir les faits", "Score, compositions et événements sont vérifiés par deux sources autorisées indépendantes."], ["02 · Calculer par programme", "Confrontations, taux, continuité et score sont calculés dans le code."], ["03 · Séparer l'interprétation", "Les relevés vérifiés sont des faits; seuls les mécanismes étayés deviennent analyse."], ["04 · Décision humaine", "L'IA rédige; l'éditeur vérifie chiffres, droits, langue et cohérence."], ["05 · Aucun média du match", "Ni image ni vidéo publique; les fichiers temporaires sont supprimés après le traitement."]], policy: "Pas de direct, compte, commentaire, contribution, profilage ou personnalisation." },
    article: { reviewed: "Relu par une personne", confidence: "Confiance de l'analyse", historicalSample: "Échantillon historique", matches: "matches", contentType: "Type de contenu", postMatch: "Analyse après-match", fact: "Fait", outcome: "Résultat", share: "Part", wins: "victoires", draws: "Nuls", change: "Changement", analysis: "Analyse", reading: "Lecture", evidence: "Confiance des preuves" },
    footer: "Event Analysis est une publication statique indépendante d'analyse historique après-match. Sans direct, compte ni suivi utilisateur.",
  },
  de: {
    pageTitle: "Fußballanalyse nach dem Spiel", pageDescription: "Ergebnisse erklärt durch Historie, Personalwechsel und Spielbelege.", skip: "Zum Inhalt",
    nav: { latest: "Aktuell", archive: "Archiv", methodology: "Methode", languages: "Sprachen" },
    home: { eyebrow: "Unabhängige Fußballanalyse · Deutsch", headline: "Das Spiel endet.\nDie Erklärung beginnt.", intro: "Kein Live-Lärm. Historie, Personalveränderungen und Spielbelege erklären das Ergebnis.", latest: "Neueste Analyse", all: "Zum Archiv", read: "Analyse lesen", numbers: "Die Zahlen", framework: "Unser Rahmen", reviewed: "Geprüft", desk: "Redaktion aktiv", scope: "Weltfußball · Nur danach", meetings: "Duelle vor dem Spiel", winRate: "historische Siegquote", winnerMinute: "Minute des Siegtreffers", emptyTitle: "Diese Ausgabe wird aufgebaut", emptyBody: "Nur übersetzte, zahlengeprüfte und menschlich redigierte Artikel erscheinen.", cards: [["Geschichte ist keine Prognose", "Duelle schaffen Kontext, ersetzen aber nicht die aktuelle Mannschaft."], ["Veränderung braucht einen Mechanismus", "Trainer, Startelf, Ausfälle und Wechsel erklären Verschiebungen."], ["Das Ergebnis braucht Belege", "Schlüsselereignisse erklären den Spielstand; Fakten und Deutung bleiben getrennt."]] },
    archive: { title: "Artikelarchiv", intro: "Historische Nachspielanalysen nach Abpfiff sortiert. Nur redaktionell geprüfte Texte.", empty: "Noch keine geprüften Artikel auf Deutsch." },
    method: { title: "Wie wir ein Spiel erklären", intro: "Daten begrenzen Fakten, redaktionelles Urteil setzt Qualität. KI genehmigt keine Veröffentlichung.", flow: "Fakten → Berechnung → Analyse → Redaktion → Veröffentlichung", steps: [["01 · Fakten sichern", "Ergebnis, Aufstellungen und Ereignisse werden mit zwei unabhängigen lizenzierten Quellen geprüft."], ["02 · Deterministisch rechnen", "Duelle, Quoten, Kontinuität und Tore berechnet der Code."], ["03 · Fakten und Deutung trennen", "Geprüfte Datensätze sind Fakten; nur belegte Mechanismen sind Analyse."], ["04 · Menschen entscheiden", "KI erstellt Entwürfe; Redakteure prüfen Zahlen, Rechte und Sprachkonsistenz."], ["05 · Keine Spielmedien", "Keine Bilder oder Videos auf öffentlichen Seiten; temporäre Dateien werden gelöscht."]], policy: "Keine Live-Ergebnisse, Konten, Kommentare, Einreichungen, Profile oder Personalisierung." },
    article: { reviewed: "Redaktionell geprüft", confidence: "Analysesicherheit", historicalSample: "Historische Stichprobe", matches: "Spiele", contentType: "Inhaltstyp", postMatch: "Analyse nach dem Spiel", fact: "Fakt", outcome: "Ergebnis", share: "Anteil", wins: "Siege", draws: "Remis", change: "Änderung", analysis: "Analyse", reading: "Deutung", evidence: "Belegsicherheit" },
    footer: "Event Analysis ist eine unabhängige statische Publikation für historische Nachspielanalysen. Keine Live-Daten, Konten oder Nutzerverfolgung.",
  },
  it: {
    pageTitle: "Analisi calcistica post-partita", pageDescription: "Risultati spiegati con precedenti, cambi di personale e prove della partita.", skip: "Vai al contenuto",
    nav: { latest: "Ultime", archive: "Archivio", methodology: "Metodo", languages: "Lingue" },
    home: { eyebrow: "Analisi indipendente · Edizione italiana", headline: "Finisce la partita.\nInizia la spiegazione.", intro: "Niente rumore in diretta. Precedenti, cambi e prove della gara spiegano il risultato.", latest: "Ultima analisi", all: "Vedi l'archivio", read: "Leggi l'analisi", numbers: "I numeri", framework: "Il nostro metodo", reviewed: "Revisionato", desk: "Redazione attiva", scope: "Calcio mondiale · Solo dopo", meetings: "incontri prima della gara", winRate: "percentuale storica di vittorie", winnerMinute: "minuto del gol decisivo", emptyTitle: "Stiamo preparando questa edizione", emptyBody: "Pubblichiamo solo articoli tradotti, verificati nei numeri e revisionati da una persona.", cards: [["La storia non è una previsione", "I precedenti danno contesto, non sostituiscono la squadra attuale."], ["Il cambiamento richiede un meccanismo", "Allenatore, titolari, assenze e sostituzioni spiegano l'equilibrio."], ["Il risultato torna alle prove", "Gli episodi spiegano il punteggio; fatti e lettura restano separati."]] },
    archive: { title: "Archivio articoli", intro: "Analisi storiche post-partita ordinate al fischio finale. Solo testi revisionati.", empty: "Non ci sono ancora articoli revisionati in italiano." },
    method: { title: "Come spieghiamo una partita", intro: "I dati fissano il confine dei fatti; il giudizio editoriale fissa la qualità. L'IA non approva la pubblicazione.", flow: "Fatti → Calcolo → Analisi → Revisione umana → Pubblicazione", steps: [["01 · Stabilire i fatti", "Risultato, formazioni ed eventi sono verificati con due fonti autorizzate indipendenti."], ["02 · Calcolare nel codice", "Precedenti, percentuali, continuità e punteggio sono calcoli deterministici."], ["03 · Separare l'interpretazione", "I record verificati sono fatti; solo meccanismi documentati diventano analisi."], ["04 · Decide una persona", "L'IA scrive bozze; l'editor verifica numeri, diritti e coerenza linguistica."], ["05 · Nessun media della partita", "Niente foto o video pubblici; il materiale temporaneo viene eliminato."]], policy: "Niente risultati live, account, commenti, invii, profilazione o personalizzazione." },
    article: { reviewed: "Revisione umana", confidence: "Affidabilità dell'analisi", historicalSample: "Campione storico", matches: "partite", contentType: "Tipo di contenuto", postMatch: "Analisi post-partita", fact: "Fatto", outcome: "Esito", share: "Quota", wins: "vittorie", draws: "Pareggi", change: "Cambiamento", analysis: "Analisi", reading: "Lettura", evidence: "Affidabilità delle prove" },
    footer: "Event Analysis è una pubblicazione statica indipendente di analisi storica post-partita. Senza live, account o tracciamento.",
  },
  ar: {
    pageTitle: "تحليل كرة القدم بعد المباراة", pageDescription: "نفسر النتيجة عبر تاريخ المواجهات وتغييرات الأفراد وأدلة المباراة.", skip: "انتقل إلى المحتوى",
    nav: { latest: "الأحدث", archive: "الأرشيف", methodology: "المنهج", languages: "اللغات" },
    home: { eyebrow: "تحليل كروي مستقل · النسخة العربية", headline: "تنتهي المباراة.\nويبدأ التفسير.", intro: "بعيداً عن ضجيج البث المباشر، نعود إلى التاريخ والتغييرات وأدلة المباراة لتفسير النتيجة.", latest: "أحدث تحليل", all: "عرض الأرشيف", read: "اقرأ التحليل", numbers: "الأرقام", framework: "إطار التحليل", reviewed: "تمت المراجعة", desk: "هيئة التحرير تعمل", scope: "كرة قدم عالمية · بعد المباراة", meetings: "مواجهات قبل المباراة", winRate: "نسبة الفوز التاريخية", winnerMinute: "دقيقة هدف الفوز", emptyTitle: "يجري إعداد هذه النسخة", emptyBody: "لا يظهر إلا المقال المترجم والمتطابق رقمياً والمراجع بشرياً.", cards: [["التاريخ ليس تنبؤاً", "المواجهات تمنح سياقاً ولا تستبدل تقييم الفريق الحالي."], ["التغيير يحتاج آلية", "المدرب والتشكيلة والغيابات والتبديلات تفسر تغير التوازن."], ["النتيجة تعود إلى الدليل", "الأحداث تفسر النتيجة مع فصل الحقائق عن القراءة."]] },
    archive: { title: "أرشيف المقالات", intro: "تحليل تاريخي بعد صافرة النهاية، ولا ينشر إلا بعد المراجعة البشرية.", empty: "لا توجد بعد مقالات عربية تمت مراجعتها." },
    method: { title: "كيف نفسر مباراة", intro: "البيانات تحدد حدود الحقيقة والحكم التحريري يحدد الجودة. الذكاء الاصطناعي لا يوافق على النشر.", flow: "حقائق ← حساب ← تحليل ← مراجعة بشرية ← نشر", steps: [["01 · تثبيت الحقائق", "تراجع النتيجة والتشكيلات والأحداث عبر مصدرين مستقلين مرخصين على الأقل."], ["02 · حساب حتمي", "تحسب المواجهات والنسب والاستمرارية والنتيجة برمجياً."], ["03 · فصل الحقيقة عن الرأي", "السجلات الموثقة حقائق، والآليات المدعومة فقط تصبح تحليلاً."], ["04 · القرار للإنسان", "يكتب الذكاء الاصطناعي مسودة ويراجع المحرر الأرقام والحقوق واللغات."], ["05 · بلا وسائط للمباراة", "لا صور أو فيديو في الصفحات العامة، وتحذف المواد المؤقتة بعد المهمة."]], policy: "لا نتائج مباشرة أو حسابات أو تعليقات أو مساهمات أو تتبع أو تخصيص." },
    article: { reviewed: "مراجعة بشرية", confidence: "ثقة التحليل", historicalSample: "العينة التاريخية", matches: "مباراة", contentType: "نوع المحتوى", postMatch: "تحليل بعد المباراة", fact: "حقيقة", outcome: "النتيجة", share: "النسبة", wins: "فوز", draws: "تعادل", change: "تغيير", analysis: "تحليل", reading: "قراءة", evidence: "ثقة الأدلة" },
    footer: "Event Analysis منصة ثابتة مستقلة للتحليل التاريخي بعد المباراة، بلا نتائج مباشرة أو حسابات أو تتبع للمستخدم.",
  },
  sv: {
    pageTitle: "Fotbollsanalys efter matchen", pageDescription: "Resultat förklaras med möteshistorik, personalförändringar och matchbevis.", skip: "Till innehållet",
    nav: { latest: "Senaste", archive: "Arkiv", methodology: "Metod", languages: "Språk" },
    home: { eyebrow: "Oberoende fotbollsanalys · Svenska", headline: "Matchen tar slut.\nFörklaringen börjar.", intro: "Inget livebrus. Historik, förändringar och matchbevis förklarar resultatet.", latest: "Senaste analys", all: "Se arkivet", read: "Läs analysen", numbers: "Siffrorna", framework: "Vår modell", reviewed: "Granskad", desk: "Redaktionen aktiv", scope: "Global fotboll · Efter match", meetings: "möten före matchen", winRate: "historisk vinstprocent", winnerMinute: "minut för segermålet", emptyTitle: "Den här utgåvan byggs", emptyBody: "Endast översatta, sifferkontrollerade och mänskligt granskade artiklar publiceras.", cards: [["Historia är ingen prognos", "Möten ger sammanhang, inte en ersättning för dagens lag."], ["Förändring kräver mekanism", "Tränare, startelva, frånvaro och byten förklarar balansen."], ["Resultatet går till bevisen", "Nyckelhändelser förklarar siffrorna; fakta hålls isär från tolkning."]] },
    archive: { title: "Artikelarkiv", intro: "Historisk efteranalys sorterad efter slutsignalen. Bara mänskligt granskade texter.", empty: "Inga granskade svenska artiklar ännu." },
    method: { title: "Så förklarar vi en match", intro: "Data sätter faktagränsen; redaktionellt omdöme sätter kvaliteten. AI godkänner inte publicering.", flow: "Fakta → Beräkning → Analys → Mänsklig granskning → Publicering", steps: [["01 · Fastställ fakta", "Resultat, lag och händelser kontrolleras mot två oberoende licensierade källor."], ["02 · Beräkna i kod", "Möten, procent, kontinuitet och mål räknas deterministiskt."], ["03 · Separera tolkning", "Verifierade poster är fakta; bara belagda mekanismer blir analys."], ["04 · Människan beslutar", "AI skriver utkast; redaktören granskar siffror, rättigheter och språk."], ["05 · Inga matchmedier", "Inga bilder eller videor publiceras; tillfälligt material raderas."]], policy: "Inga liveresultat, konton, kommentarer, bidrag, profiler eller personalisering." },
    article: { reviewed: "Mänskligt granskad", confidence: "Analyssäkerhet", historicalSample: "Historiskt urval", matches: "matcher", contentType: "Innehållstyp", postMatch: "Analys efter match", fact: "Fakta", outcome: "Utfall", share: "Andel", wins: "vinster", draws: "Oavgjorda", change: "Förändring", analysis: "Analys", reading: "Tolkning", evidence: "Bevissäkerhet" },
    footer: "Event Analysis är en oberoende statisk publikation för historisk analys efter matchen. Inga liveresultat, konton eller spårning.",
  },
  nl: {
    pageTitle: "Voetbalanalyse na de wedstrijd", pageDescription: "Uitslagen verklaard met onderlinge historie, personele wijzigingen en wedstrijdbewijs.", skip: "Naar inhoud",
    nav: { latest: "Nieuw", archive: "Archief", methodology: "Methode", languages: "Talen" },
    home: { eyebrow: "Onafhankelijke voetbalanalyse · Nederlands", headline: "De wedstrijd stopt.\nDe uitleg begint.", intro: "Geen live-ruis. Historie, personele veranderingen en bewijs uit de wedstrijd verklaren de uitslag.", latest: "Laatste analyse", all: "Bekijk archief", read: "Lees analyse", numbers: "De cijfers", framework: "Ons kader", reviewed: "Beoordeeld", desk: "Redactie actief", scope: "Wereldvoetbal · Na afloop", meetings: "duels voor de wedstrijd", winRate: "historisch winstpercentage", winnerMinute: "minuut van winnende goal", emptyTitle: "Deze editie wordt opgebouwd", emptyBody: "Alleen vertaalde, cijfermatig gecontroleerde en menselijk beoordeelde artikelen verschijnen.", cards: [["Historie is geen voorspelling", "Duels geven context, maar vervangen het huidige team niet."], ["Verandering vraagt een mechanisme", "Coach, opstelling, afwezigen en wissels verklaren de balans."], ["De uitslag volgt het bewijs", "Sleutelmomenten verklaren de score; feiten en duiding blijven apart."]] },
    archive: { title: "Artikelarchief", intro: "Historische analyse na het laatste fluitsignaal. Alleen menselijk beoordeeld werk.", empty: "Nog geen beoordeelde artikelen in het Nederlands." },
    method: { title: "Hoe wij een wedstrijd verklaren", intro: "Data begrenzen feiten; redactioneel oordeel bepaalt kwaliteit. AI keurt geen publicatie goed.", flow: "Feiten → Berekening → Analyse → Menselijke controle → Publicatie", steps: [["01 · Feiten vaststellen", "Score, opstellingen en momenten worden getoetst aan twee onafhankelijke licentiebronnen."], ["02 · Deterministisch rekenen", "Duels, percentages, continuïteit en score worden in code berekend."], ["03 · Duiding scheiden", "Geverifieerde registraties zijn feiten; alleen onderbouwde mechanismen zijn analyse."], ["04 · Mensen beslissen", "AI maakt concepten; redacteuren controleren cijfers, rechten en talen."], ["05 · Geen wedstrijdmedia", "Geen foto's of video; tijdelijke bestanden worden na de taak verwijderd."]], policy: "Geen livescores, accounts, reacties, inzendingen, profielen of personalisatie." },
    article: { reviewed: "Menselijk beoordeeld", confidence: "Zekerheid analyse", historicalSample: "Historische steekproef", matches: "wedstrijden", contentType: "Inhoudstype", postMatch: "Analyse na afloop", fact: "Feit", outcome: "Uitkomst", share: "Aandeel", wins: "zeges", draws: "Gelijk", change: "Verandering", analysis: "Analyse", reading: "Duiding", evidence: "Zekerheid bewijs" },
    footer: "Event Analysis is een onafhankelijke statische publicatie voor historische analyse na wedstrijden. Geen livescores, accounts of tracking.",
  },
  tr: {
    pageTitle: "Maç sonrası futbol analizi", pageDescription: "Sonucu geçmiş karşılaşmalar, kadro değişimleri ve maç kanıtlarıyla açıklıyoruz.", skip: "İçeriğe geç",
    nav: { latest: "Son", archive: "Arşiv", methodology: "Yöntem", languages: "Diller" },
    home: { eyebrow: "Bağımsız futbol analizi · Türkçe", headline: "Maç biter.\nAçıklama başlar.", intro: "Canlı yayın gürültüsü yok. Geçmiş, kadro değişimleri ve maç kanıtları sonucu açıklar.", latest: "Son analiz", all: "Arşivi gör", read: "Analizi oku", numbers: "Sayılar", framework: "Analiz çerçevemiz", reviewed: "İncelendi", desk: "Editör masası aktif", scope: "Dünya futbolu · Maç sonrası", meetings: "maç öncesi karşılaşma", winRate: "tarihi galibiyet oranı", winnerMinute: "galibiyet golü dakikası", emptyTitle: "Bu sürüm hazırlanıyor", emptyBody: "Yalnızca çevrilmiş, sayıları tutarlı ve insan tarafından incelenmiş yazılar yayımlanır.", cards: [["Tarih tahmin değildir", "Geçmiş maçlar bağlam verir, güncel takımı ikame etmez."], ["Değişim mekanizma ister", "Teknik adam, ilk 11, eksikler ve değişiklikler dengeyi açıklar."], ["Sonuç kanıta döner", "Kilit olaylar skoru açıklar; olgu ve yorum ayrılır."]] },
    archive: { title: "Yazı arşivi", intro: "Son düdüğe göre sıralanan maç sonrası tarih analizi. Yalnız insan incelemesinden geçenler.", empty: "Henüz Türkçe incelenmiş yazı yok." },
    method: { title: "Bir maçı nasıl açıklıyoruz", intro: "Veri olgunun sınırını, editoryal karar kaliteyi belirler. Yapay zekâ yayını onaylamaz.", flow: "Olgular → Hesap → Analiz → İnsan incelemesi → Yayın", steps: [["01 · Olguları kur", "Skor, kadrolar ve olaylar iki bağımsız lisanslı kaynaktan doğrulanır."], ["02 · Kodla hesapla", "Karşılaşmalar, oranlar, süreklilik ve skor deterministik hesaplanır."], ["03 · Yorumu ayır", "Doğrulanmış kayıt olgudur; yalnız kanıtlı mekanizma analizdir."], ["04 · İnsan karar verir", "AI taslak yazar; editör sayıları, hakları ve dil tutarlılığını denetler."], ["05 · Maç medyası yok", "Görsel ve video yayımlanmaz; geçici dosyalar iş sonunda silinir."]], policy: "Canlı skor, hesap, yorum, gönderi, profil veya kişiselleştirme yok." },
    article: { reviewed: "İnsan incelemesi", confidence: "Analiz güveni", historicalSample: "Tarihi örneklem", matches: "maç", contentType: "İçerik türü", postMatch: "Maç sonrası analiz", fact: "Olgu", outcome: "Sonuç", share: "Pay", wins: "galibiyet", draws: "Beraberlik", change: "Değişim", analysis: "Analiz", reading: "Yorum", evidence: "Kanıt güveni" },
    footer: "Event Analysis maç sonrası tarih analizine odaklanan bağımsız statik bir yayındır. Canlı skor, hesap veya izleme yoktur.",
  },
  pl: {
    pageTitle: "Analiza piłki po meczu", pageDescription: "Wyjaśniamy wynik przez historię spotkań, zmiany kadrowe i dowody z meczu.", skip: "Do treści",
    nav: { latest: "Najnowsze", archive: "Archiwum", methodology: "Metoda", languages: "Języki" },
    home: { eyebrow: "Niezależna analiza · Wersja polska", headline: "Mecz się kończy.\nWyjaśnienie zaczyna.", intro: "Bez szumu na żywo. Historia, zmiany kadrowe i dowody z meczu wyjaśniają wynik.", latest: "Najnowsza analiza", all: "Zobacz archiwum", read: "Czytaj analizę", numbers: "Liczby", framework: "Nasz schemat", reviewed: "Sprawdzone", desk: "Redakcja aktywna", scope: "Futbol światowy · Po meczu", meetings: "spotkań przed meczem", winRate: "historyczny odsetek zwycięstw", winnerMinute: "minuta zwycięskiego gola", emptyTitle: "Ta wersja jest przygotowywana", emptyBody: "Publikujemy wyłącznie teksty przetłumaczone, zgodne liczbowo i sprawdzone przez człowieka.", cards: [["Historia nie jest prognozą", "Mecze dają kontekst, ale nie zastępują oceny obecnego zespołu."], ["Zmiana wymaga mechanizmu", "Trener, skład, absencje i zmiany wyjaśniają równowagę."], ["Wynik wraca do dowodów", "Kluczowe zdarzenia tłumaczą wynik; fakty są oddzielone od opinii."]] },
    archive: { title: "Archiwum artykułów", intro: "Historyczne analizy po końcowym gwizdku. Tylko teksty sprawdzone przez człowieka.", empty: "Brak sprawdzonych artykułów po polsku." },
    method: { title: "Jak wyjaśniamy mecz", intro: "Dane wyznaczają granice faktów, redakcja standard jakości. AI nie zatwierdza publikacji.", flow: "Fakty → Obliczenia → Analiza → Redakcja → Publikacja", steps: [["01 · Ustal fakty", "Wynik, składy i wydarzenia sprawdzają dwa niezależne licencjonowane źródła."], ["02 · Policz w kodzie", "Spotkania, procenty, ciągłość i wynik są obliczane deterministycznie."], ["03 · Oddziel interpretację", "Zweryfikowane zapisy są faktami; tylko mechanizmy z dowodami są analizą."], ["04 · Decyduje człowiek", "AI tworzy szkic; redaktor sprawdza liczby, prawa i języki."], ["05 · Bez mediów meczowych", "Nie publikujemy zdjęć ani wideo; pliki tymczasowe są usuwane."]], policy: "Bez wyników live, kont, komentarzy, zgłoszeń, profili i personalizacji." },
    article: { reviewed: "Sprawdzone przez człowieka", confidence: "Pewność analizy", historicalSample: "Próba historyczna", matches: "meczów", contentType: "Typ treści", postMatch: "Analiza po meczu", fact: "Fakt", outcome: "Wynik", share: "Udział", wins: "zwycięstwa", draws: "Remisy", change: "Zmiana", analysis: "Analiza", reading: "Odczyt", evidence: "Pewność dowodów" },
    footer: "Event Analysis to niezależna statyczna publikacja historycznych analiz po meczu. Bez live, kont i śledzenia użytkownika.",
  },
  hr: {
    pageTitle: "Nogometna analiza nakon utakmice", pageDescription: "Rezultat objašnjavamo poviješću susreta, promjenama kadra i dokazima iz utakmice.", skip: "Na sadržaj",
    nav: { latest: "Najnovije", archive: "Arhiva", methodology: "Metoda", languages: "Jezici" },
    home: { eyebrow: "Neovisna nogometna analiza · Hrvatski", headline: "Utakmica završava.\nObjašnjenje počinje.", intro: "Bez buke uživo. Povijest, promjene kadra i dokazi objašnjavaju rezultat.", latest: "Najnovija analiza", all: "Pogledaj arhivu", read: "Čitaj analizu", numbers: "Brojevi", framework: "Naš okvir", reviewed: "Pregledano", desk: "Redakcija aktivna", scope: "Svjetski nogomet · Nakon utakmice", meetings: "susreta prije utakmice", winRate: "povijesni postotak pobjeda", winnerMinute: "minuta pobjedničkog gola", emptyTitle: "Ovo izdanje se priprema", emptyBody: "Objavljujemo samo prevedene, brojčano usklađene i ljudski pregledane tekstove.", cards: [["Povijest nije prognoza", "Susreti daju kontekst, ne zamjenjuju procjenu sadašnje momčadi."], ["Promjena traži mehanizam", "Trener, sastav, izostanci i zamjene objašnjavaju ravnotežu."], ["Rezultat se vraća dokazima", "Ključni događaji objašnjavaju rezultat; činjenice i tumačenje su odvojeni."]] },
    archive: { title: "Arhiva članaka", intro: "Povijesna analiza nakon završnog zvižduka. Samo ljudski pregledani tekstovi.", empty: "Još nema pregledanih članaka na hrvatskom." },
    method: { title: "Kako objašnjavamo utakmicu", intro: "Podaci omeđuju činjenice, urednička prosudba određuje kvalitetu. AI ne odobrava objavu.", flow: "Činjenice → Izračun → Analiza → Ljudski pregled → Objava", steps: [["01 · Utvrdi činjenice", "Rezultat, sastavi i događaji provjeravaju se kroz dva neovisna licencirana izvora."], ["02 · Izračunaj u kodu", "Susreti, postoci, kontinuitet i rezultat računaju se deterministički."], ["03 · Odvoji tumačenje", "Provjereni zapisi su činjenice; samo dokazani mehanizmi postaju analiza."], ["04 · Čovjek odlučuje", "AI piše nacrt; urednik provjerava brojke, prava i jezike."], ["05 · Bez medija utakmice", "Ne objavljujemo slike ni video; privremene datoteke brišemo."]], policy: "Nema rezultata uživo, računa, komentara, prijava, profiliranja ni personalizacije." },
    article: { reviewed: "Ljudski pregledano", confidence: "Pouzdanost analize", historicalSample: "Povijesni uzorak", matches: "utakmica", contentType: "Vrsta sadržaja", postMatch: "Analiza nakon utakmice", fact: "Činjenica", outcome: "Ishod", share: "Udio", wins: "pobjede", draws: "Remiji", change: "Promjena", analysis: "Analiza", reading: "Tumačenje", evidence: "Pouzdanost dokaza" },
    footer: "Event Analysis je neovisna statična publikacija povijesne analize nakon utakmice. Bez rezultata uživo, računa ili praćenja.",
  },
  sr: {
    pageTitle: "Фудбалска анализа после меча", pageDescription: "Резултат објашњавамо историјом сусрета, променама састава и доказима из меча.", skip: "На садржај",
    nav: { latest: "Најновије", archive: "Архива", methodology: "Метод", languages: "Језици" },
    home: { eyebrow: "Независна фудбалска анализа · Српски", headline: "Меч се завршава.\nОбјашњење почиње.", intro: "Без буке уживо. Историја, промене састава и докази из меча објашњавају резултат.", latest: "Најновија анализа", all: "Погледај архиву", read: "Читај анализу", numbers: "Бројеви", framework: "Наш оквир", reviewed: "Прегледано", desk: "Редакција ради", scope: "Светски фудбал · После меча", meetings: "сусрета пре меча", winRate: "историјски проценат победа", winnerMinute: "минут победничког гола", emptyTitle: "Ово издање се припрема", emptyBody: "Објављујемо само преведене, бројчано усклађене и људски прегледане текстове.", cards: [["Историја није прогноза", "Сусрети дају контекст, не замењују процену садашњег тима."], ["Промена тражи механизам", "Тренер, састав, изостанци и измене објашњавају равнотежу."], ["Резултат се враћа доказима", "Кључни догађаји објашњавају скор; чињенице и тумачење су одвојени."]] },
    archive: { title: "Архива чланака", intro: "Историјска анализа после последњег звиждука. Само људски прегледани текстови.", empty: "Још нема прегледаних чланака на српском." },
    method: { title: "Како објашњавамо меч", intro: "Подаци ограничавају чињенице, уреднички суд одређује квалитет. AI не одобрава објаву.", flow: "Чињенице → Рачун → Анализа → Људски преглед → Објава", steps: [["01 · Утврди чињенице", "Резултат, састави и догађаји проверавају се кроз два независна лиценцирана извора."], ["02 · Израчунај у коду", "Сусрети, проценти, континуитет и резултат рачунају се детерминистички."], ["03 · Одвоји тумачење", "Проверени записи су чињенице; само доказани механизми постају анализа."], ["04 · Човек одлучује", "AI пише нацрт; уредник проверава бројке, права и језике."], ["05 · Без медија меча", "Не објављујемо слике ни видео; привремене датотеке се бришу."]], policy: "Нема резултата уживо, налога, коментара, пријава, профила или персонализације." },
    article: { reviewed: "Људски прегледано", confidence: "Поузданост анализе", historicalSample: "Историјски узорак", matches: "мечева", contentType: "Врста садржаја", postMatch: "Анализа после меча", fact: "Чињеница", outcome: "Исход", share: "Удео", wins: "победе", draws: "Нерешено", change: "Промена", analysis: "Анализа", reading: "Тумачење", evidence: "Поузданост доказа" },
    footer: "Event Analysis је независна статична публикација за историјску анализу после меча. Без уживо резултата, налога или праћења.",
  },
  uk: {
    pageTitle: "Футбольний аналіз після матчу", pageDescription: "Пояснюємо результат через історію зустрічей, зміни складу та докази матчу.", skip: "До матеріалу",
    nav: { latest: "Нове", archive: "Архів", methodology: "Метод", languages: "Мови" },
    home: { eyebrow: "Незалежний футбольний аналіз · Українська", headline: "Матч завершено.\nПояснення починається.", intro: "Без шуму наживо. Історія, кадрові зміни та докази матчу пояснюють результат.", latest: "Останній аналіз", all: "Переглянути архів", read: "Читати аналіз", numbers: "Цифри", framework: "Наша схема", reviewed: "Перевірено", desk: "Редакція працює", scope: "Світовий футбол · Після матчу", meetings: "зустрічей до матчу", winRate: "історичний відсоток перемог", winnerMinute: "хвилина переможного гола", emptyTitle: "Ця версія готується", emptyBody: "Публікуємо лише перекладені, чисельно узгоджені та перевірені людиною матеріали.", cards: [["Історія не є прогнозом", "Зустрічі дають контекст, але не замінюють оцінку нинішньої команди."], ["Зміна потребує механізму", "Тренер, старт, втрати й заміни пояснюють рух балансу."], ["Результат повертається до доказів", "Ключові події пояснюють рахунок; факти відокремлені від висновків."]] },
    archive: { title: "Архів статей", intro: "Історичний аналіз після фінального свистка. Лише матеріали з ручною перевіркою.", empty: "Перевірених статей українською поки немає." },
    method: { title: "Як ми пояснюємо матч", intro: "Дані задають межі фактів, редактор — стандарт якості. AI не затверджує публікацію.", flow: "Факти → Розрахунок → Аналіз → Редактор → Публікація", steps: [["01 · Встановити факти", "Рахунок, склади та події звіряють щонайменше два незалежні ліцензовані джерела."], ["02 · Рахувати програмно", "Зустрічі, відсотки, спадкоємність і рахунок обчислює код."], ["03 · Відділити висновки", "Перевірені записи — факти; лише обґрунтовані механізми є аналізом."], ["04 · Рішення за людиною", "AI пише чернетку, редактор перевіряє цифри, права та узгодженість мов."], ["05 · Без медіа матчу", "На сайті немає фото чи відео; тимчасові матеріали видаляються."]], policy: "Немає live-рахунків, акаунтів, коментарів, заявок, стеження чи персоналізації." },
    article: { reviewed: "Перевірено людиною", confidence: "Упевненість аналізу", historicalSample: "Історична вибірка", matches: "матчів", contentType: "Тип матеріалу", postMatch: "Аналіз після матчу", fact: "Факт", outcome: "Підсумок", share: "Частка", wins: "перемоги", draws: "Нічиї", change: "Зміна", analysis: "Аналіз", reading: "Висновок", evidence: "Упевненість у доказах" },
    footer: "Event Analysis — незалежне статичне видання про історичний аналіз після матчу. Без live-рахунків, акаунтів і стеження.",
  },
  fa: {
    pageTitle: "تحلیل فوتبال پس از بازی", pageDescription: "نتیجه را با تاریخچه دیدارها، تغییرات نفرات و شواهد مسابقه توضیح می‌دهیم.", skip: "رفتن به محتوا",
    nav: { latest: "تازه‌ها", archive: "آرشیو", methodology: "روش", languages: "زبان‌ها" },
    home: { eyebrow: "تحلیل مستقل فوتبال · فارسی", headline: "بازی تمام می‌شود.\nتوضیح آغاز می‌شود.", intro: "بدون هیاهوی زنده؛ تاریخچه، تغییرات نفرات و شواهد بازی نتیجه را توضیح می‌دهند.", latest: "تازه‌ترین تحلیل", all: "دیدن آرشیو", read: "خواندن تحلیل", numbers: "عددها", framework: "چارچوب تحلیل", reviewed: "بازبینی‌شده", desk: "تحریریه فعال", scope: "فوتبال جهان · پس از بازی", meetings: "دیدار پیش از مسابقه", winRate: "درصد برد تاریخی", winnerMinute: "دقیقه گل پیروزی", emptyTitle: "این نسخه در حال آماده‌سازی است", emptyBody: "فقط مقاله ترجمه‌شده، همسان از نظر عددی و بازبینی‌شده به دست انسان منتشر می‌شود.", cards: [["تاریخ پیش‌بینی نیست", "دیدارها زمینه می‌دهند اما جای ارزیابی تیم فعلی را نمی‌گیرند."], ["تغییر به سازوکار نیاز دارد", "مربی، ترکیب، غیبت‌ها و تعویض‌ها جابه‌جایی تعادل را توضیح می‌دهند."], ["نتیجه به شواهد بازمی‌گردد", "رویدادها نتیجه را توضیح می‌دهند و واقعیت از برداشت جداست."]] },
    archive: { title: "آرشیو مقاله‌ها", intro: "تحلیل تاریخی پس از سوت پایان؛ فقط نوشته‌های بازبینی‌شده به دست انسان.", empty: "هنوز مقاله بازبینی‌شده فارسی نداریم." },
    method: { title: "چگونه یک بازی را توضیح می‌دهیم", intro: "داده مرز واقعیت و داوری سردبیری کیفیت را تعیین می‌کند. هوش مصنوعی انتشار را تأیید نمی‌کند.", flow: "واقعیت ← محاسبه ← تحلیل ← بازبینی انسانی ← انتشار", steps: [["01 · تثبیت واقعیت", "نتیجه، ترکیب و رویدادها با دو منبع مستقل دارای مجوز بررسی می‌شوند."], ["02 · محاسبه قطعی", "دیدارها، درصدها، تداوم و نتیجه در کد محاسبه می‌شوند."], ["03 · جداسازی برداشت", "رکورد تأییدشده واقعیت است؛ فقط سازوکار مستند تحلیل می‌شود."], ["04 · تصمیم با انسان", "AI پیش‌نویس می‌نویسد و سردبیر عددها، حقوق و زبان‌ها را بررسی می‌کند."], ["05 · بدون رسانه مسابقه", "تصویر یا ویدئو منتشر نمی‌شود و فایل موقت پس از کار حذف می‌شود."]], policy: "بدون نتیجه زنده، حساب، نظر، ارسال مطلب، پروفایل یا شخصی‌سازی." },
    article: { reviewed: "بازبینی انسانی", confidence: "اطمینان تحلیل", historicalSample: "نمونه تاریخی", matches: "بازی", contentType: "نوع محتوا", postMatch: "تحلیل پس از بازی", fact: "واقعیت", outcome: "نتیجه", share: "سهم", wins: "برد", draws: "تساوی", change: "تغییر", analysis: "تحلیل", reading: "برداشت", evidence: "اطمینان شواهد" },
    footer: "Event Analysis یک نشریه ایستای مستقل برای تحلیل تاریخی پس از بازی است؛ بدون نتیجه زنده، حساب یا ردیابی کاربر.",
  },
  id: {
    pageTitle: "Analisis sepak bola setelah laga", pageDescription: "Menjelaskan hasil melalui riwayat pertemuan, perubahan personel, dan bukti pertandingan.", skip: "Ke isi",
    nav: { latest: "Terbaru", archive: "Arsip", methodology: "Metode", languages: "Bahasa" },
    home: { eyebrow: "Analisis sepak bola independen · Indonesia", headline: "Laga berakhir.\nPenjelasan dimulai.", intro: "Tanpa hiruk-pikuk langsung. Riwayat, perubahan personel, dan bukti laga menjelaskan hasil.", latest: "Analisis terbaru", all: "Lihat arsip", read: "Baca analisis", numbers: "Angka", framework: "Kerangka kami", reviewed: "Ditinjau", desk: "Redaksi aktif", scope: "Sepak bola dunia · Seusai laga", meetings: "pertemuan sebelum laga", winRate: "persentase kemenangan historis", winnerMinute: "menit gol kemenangan", emptyTitle: "Edisi ini sedang disiapkan", emptyBody: "Hanya artikel yang sudah diterjemahkan, konsisten angkanya, dan ditinjau manusia yang diterbitkan.", cards: [["Riwayat bukan ramalan", "Pertemuan memberi konteks, bukan pengganti penilaian tim saat ini."], ["Perubahan perlu mekanisme", "Pelatih, susunan, absensi, dan pergantian menjelaskan keseimbangan."], ["Hasil kembali ke bukti", "Peristiwa kunci menjelaskan skor; fakta dan tafsir dipisahkan."]] },
    archive: { title: "Arsip artikel", intro: "Analisis historis seusai peluit akhir. Hanya tulisan yang ditinjau manusia.", empty: "Belum ada artikel Bahasa Indonesia yang ditinjau." },
    method: { title: "Cara kami menjelaskan laga", intro: "Data menetapkan batas fakta; penilaian redaksi menetapkan mutu. AI tidak menyetujui penerbitan.", flow: "Fakta → Hitung → Analisis → Tinjauan manusia → Terbit", steps: [["01 · Tetapkan fakta", "Skor, susunan, dan peristiwa diperiksa pada dua sumber berlisensi yang independen."], ["02 · Hitung dalam kode", "Pertemuan, persentase, kesinambungan, dan skor dihitung secara deterministik."], ["03 · Pisahkan tafsir", "Catatan terverifikasi adalah fakta; hanya mekanisme berbukti menjadi analisis."], ["04 · Manusia memutuskan", "AI membuat draf; editor memeriksa angka, hak, dan konsistensi bahasa."], ["05 · Tanpa media laga", "Tidak ada foto atau video publik; berkas sementara dihapus setelah tugas."]], policy: "Tanpa skor langsung, akun, komentar, kiriman, profil, atau personalisasi." },
    article: { reviewed: "Ditinjau manusia", confidence: "Keyakinan analisis", historicalSample: "Sampel historis", matches: "laga", contentType: "Jenis konten", postMatch: "Analisis seusai laga", fact: "Fakta", outcome: "Hasil", share: "Porsi", wins: "menang", draws: "Seri", change: "Perubahan", analysis: "Analisis", reading: "Tafsiran", evidence: "Keyakinan bukti" },
    footer: "Event Analysis adalah publikasi statis independen untuk analisis historis seusai laga. Tanpa skor langsung, akun, atau pelacakan pengguna.",
  },
};
